---
# <!-- # --- -->
title: "Final_project_data_vis"
subtitle: "25-spring-IDC6700"
author: "Alex Baekey"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  pdf_document:
    latex_engine: xelatex
    toc: true
    number_sections: true
    toc_depth: 6
    highlight: tango
  html_document:
    toc: yes
urlcolor: blue
---

<!-- # Fix the bullet points and the orange and cherry data set questions -->


```{r, setup, include=FALSE}
knitr::opts_chunk$set(
  cache = FALSE, # if TRUE knitr will cache results to reuse in future knits
  fig.width = 6, # the width for plots created by code chunk
  fig.height = 4.5, # the height for plots created by code chunk
  fig.align = 'center', # how to align graphics. 'left', 'right', 'center'
  dpi = 150, 
  # results = 'asis', # knitr passes through results without reformatting
  echo = TRUE, # if FALSE knitr won't display code in chunk above it's results
  message = TRUE, # if FALSE knitr won't display messages generated by code
  strip.white = TRUE, # if FALSE knitr won't remove white spaces at beg or end
  warning = FALSE) # if FALSE knitr won't display warning messages in the doc
```



```{r}
# Interactive sunburst plot of bacterial taxonomy
# https://cran.r-project.org/web/packages/sunburstR/vignettes/sunburst-2-0-0.html
# https://www.geeksforgeeks.org/creating-sunburst-charts-for-hierarchical-data-in-r/

library(data.table)
#options(repos = c(CRAN = "https://cloud.r-project.org"))
#install.packages("sunburstR")
library(dplyr)
library(sunburstR)
library(htmlwidgets) 

# taxa.csv is just a temporary, filtered copy of GenomeData.csv, without the non-taxonomic columns
#tax <- fread("/home/ab/GitHub/Bacterial-Genomic-Analysis-Data-Visualization/processedData/taxa.csv", sep = ",", header = TRUE)

df <- fread("/home/ab/GitHub/Bacterial-Genomic-Analysis-Data-Visualization/processedData/genomeData.csv", sep = ",", header = TRUE)
taxonomy_cols <- c("Domain", "Kingdom", "Phylum",
  "Class", "Order", "Family",
  "Genus", "Species")
tax <- df %>% select(all_of(taxonomy_cols))

tax[, N := .N, by = .(Domain, Kingdom, Phylum, Class, Order, Family, Genus)]
leaf_counts <- unique(tax[, .(Domain, Kingdom, Phylum, Class, Order, Family, Genus, N)])
leaf_counts[, path := paste(Domain, Kingdom, Phylum, Class, Order, Family, Genus, sep = "-")]

sb <- sunburst(
  leaf_counts[, .(path, N)],
  count = TRUE,
  legend = FALSE,
  height = 600, width = 600
)

saveWidget(sb, file = "sunburst.html", selfcontained = TRUE)

```


```{r}

# Labeled dendrogram

library(data.table)
library(igraph)
library(ggraph)
library(ggplot2)
library(dplyr)

#tax <- fread("/home/ab/GitHub/Bacterial-Genomic-Analysis-Data-Visualization/processedData/taxa.csv")

df <- fread("/home/ab/GitHub/Bacterial-Genomic-Analysis-Data-Visualization/processedData/genomeData.csv", sep = ",", header = TRUE)
taxonomy_cols <- c("Domain", "Kingdom", "Phylum",
  "Class", "Order", "Family",
  "Genus", "Species")
tax <- df %>% select(all_of(taxonomy_cols))

tax[, N := .N, by = .(Domain, Kingdom, Phylum, Class, Order, Family, Genus)]
leaf_counts <- unique(tax[, .(Domain, Kingdom, Phylum, Class, Order, Family, Genus)])

edges <- rbindlist(list(
  leaf_counts[, .(from = Domain, to = Kingdom)],
  leaf_counts[, .(from = Kingdom, to = Phylum)],
  leaf_counts[, .(from = Phylum, to = Class)],
  leaf_counts[, .(from = Class, to = Order)],
  leaf_counts[, .(from = Order, to = Family)],
  leaf_counts[, .(from = Family, to = Genus)]
))
edges <- unique(edges[!is.na(from) & !is.na(to)])
#edges <- unique(edges[(from) & (to)])
edges <- rbind(data.table(from = "All strains", to = unique(leaf_counts$Domain)), edges)

g <- graph_from_data_frame(edges, directed = TRUE)

V(g)$rank <- case_when(
  V(g)$name == "All strains"              ~ "Root",
  V(g)$name %in% leaf_counts$Domain       ~ "Domain",
  V(g)$name %in% leaf_counts$Kingdom      ~ "Kingdom",
  V(g)$name %in% leaf_counts$Phylum       ~ "Phylum",
  V(g)$name %in% leaf_counts$Class        ~ "Class",
  V(g)$name %in% leaf_counts$Order        ~ "Order",
  V(g)$name %in% leaf_counts$Family       ~ "Family",
  TRUE                                    ~ "Genus"
)

correct_order <- c("All strains", "Domain", "Kingdom",
  "Phylum", "Class", "Order",
  "Family", "Genus")

p <- ggraph(g, layout = "dendrogram") +
  geom_edge_diagonal() +
  geom_node_text(
    aes(label = name, colour = rank),
    hjust = -0.1, 
    size = 5,
    angle = 30 
  ) +
  scale_colour_brewer(palette = "Dark2", name = "Rank", limits=correct_order) +
  ggtitle("bacterial taxonomy") +
  theme_void(base_size = 11) +
  scale_x_continuous(expand = expansion(mult = c(0.05, 0.15))) + # text was getting cut off on right side
  theme(
    #legend.position = "right",
    legend.position = c(0.07, 0.85),
    plot.background = element_rect(fill = "white", colour = NA),
    panel.background = element_rect(fill = "white", colour = NA)
  )
ggsave("dendrogram.png", p, width = 15, height = 9, dpi = 300)

```